spring:
   application:
   name: eureka-service
   
server:
   port: 8761   

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false 
   instance:
      hostname: localhost
   serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/