spring:
   jpa:
      hibernate:
         ddl_auto: create
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      
   datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password
      
   batch:
      job:
         enabled: false
   h2:
      console:
         enabled: true
   
inputFile: src/main/resources/customers.csv