server:
   port: 8762 
   
spring:
   application:
      name: api-gateway

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
   serviceUrl:
      defaultZone: http://localhost:8761:eureka/
      
zuul:
   prefix: /api
   routes:
      employeeService:
         path: /employees/**
         serviceId: employee-service
         